apiVersion: v1
name: jitsi-meet
version: 0.1.2
appVersion: "stable-4857"
description: Jitsi Meet is an open source JavaScript WebRTC application and can be used for videoconferencing
keywords:
  - conference
  - meeting
  - calls
  - webrtc
home: https://jitsi.org/jitsi-meet/
icon: https://335wvf48o1332cksy23mw1pj-wpengine.netdna-ssl.com/wp-content/themes/jitsi/images/logo-web-2020.png
sources:
  - https://github.com/jitsi/docker-jitsi-meet
maintainers:
  - name: jasper-ben
    email: jasper@fancydomain.eu
