jicofo:
  userAuth:
    enabled: true
    name: "focus"
    secret: dG90bw==
  componentSecret: dG90bw==
  environment:
    - name: TZ
      value: Europe/Amsterdam
    - name: JVB_BREWERY_MUC
      value: jvbbrewery
    - name: XMPP_DOMAIN
      value: meet.jitsi
    - name: XMPP_AUTH_DOMAIN
      value: auth.meet.jitsi
    - name: XMPP_INTERNAL_MUC_DOMAIN
      value: internal-muc.meet.jitsi
jvb:
  userAuth:
    enabled: true
    name: "jvb"
    secret: dG90bw==
  environment:
    - name: TZ
      value: Europe/Amsterdam
    - name: JVB_BREWERY_MUC
      value: jvbbrewery
    - name: XMPP_DOMAIN
      value: meet.jitsi
    - name: XMPP_AUTH_DOMAIN
      value: auth.meet.jitsi
    - name: XMPP_MUC_DOMAIN
      value: muc.meet.jitsi
    - name: XMPP_INTERNAL_MUC_DOMAIN
      value: internal-muc.meet.jitsi
    - name: JVB_STUN_SERVERS
      value: stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302
    - name: JVB_TCP_HARVESTER_DISABLED
      value: "true"
    - name: DOCKER_HOST_ADDRESS
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP

prosody:
  environment:
    - name: JVB_TCP_HARVESTER_DISABLED
      value: "true"
    - name: TZ
      value: Europe/Amsterdam
    - name: JVB_BREWERY_MUC
      value: jvbbrewery
    - name: XMPP_DOMAIN
      value: meet.jitsi
    - name: XMPP_AUTH_DOMAIN
      value: auth.meet.jitsi
    - name: XMPP_INTERNAL_MUC_DOMAIN
      value: internal-muc.meet.jitsi
    - name: JVB_TCP_HARVESTER_DISABLED
      value: "true"
    - name: XMPP_MUC_DOMAIN
      value: muc.meet.jitsi

web:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "letsencrypt"
    hosts:
      - host: jitsi.meat-project.tk
        paths:
          - "/"
    tls:
      - hosts:
          - jitsi.meat-project.tk
        secretName: jitsi-web
  environment:
    - name: XMPP_DOMAIN
      value: meet.jitsi
    - name: XMPP_AUTH_DOMAIN
      value: auth.meet.jitsi
    - name: XMPP_INTERNAL_MUC_DOMAIN
      value: internal-muc.meet.jitsi
    - name: XMPP_MUC_DOMAIN
      value: muc.meet.jitsi
    - name: TZ
      value: America/Los_Angeles
    - name: JVB_TCP_HARVESTER_DISABLED
      value: "true"